### ISSUE TITLE
请问这个支持其他substrate框架开发链的离线签名吗?

### ISSUE THREAD

**Issue by zenghq3** [JFJun/substrate-go#1]
我想对Stafi做离线签名,然后发现这个sdk有stafi的地址生成,没有签名

**Comment by JFJun** [comment]
我还没有研究，目前是不支持的

**Comment by JFJun** [comment]
> 我想对Stafi做离线签名,然后发现这个sdk有stafi的地址生成,没有签名

我还没有研究，目前是不支持的

**Comment by zenghq3** [comment]
谢谢了
