### ISSUE TITLE
地址上只有一个dot时不让转账

### ISSUE THREAD

**Issue by zhp1254** [JFJun/substrate-go#2]
地址上只有一个dot 转0.9个节点报错，有办法可以把这种都转出来 吗

{
  "jsonrpc": "2.0",
  "error": {
    "code": 1010,
    "message": "Invalid Transaction",
    "data": "Inability to pay some fees (e.g. account balance too low)"
  },
  "id": 1
}

**Comment by JFJun** [comment]
> 地址上只有一个dot 转0.9个节点报错，有办法可以把这种都转出来 吗
> 
> {
> "jsonrpc": "2.0",
> "error": {
> "code": 1010,
> "message": "Invalid Transaction",
> "data": "Inability to pay some fees (e.g. account balance too low)"
> },
> "id": 1
> }



> 地址上只有一个dot 转0.9个节点报错，有办法可以把这种都转出来 吗
> 
> {
> "jsonrpc": "2.0",
> "error": {
> "code": 1010,
> "message": "Invalid Transaction",
> "data": "Inability to pay some fees (e.g. account balance too low)"
> },
> "id": 1
> }

只有一个dot是无法转出来的，你的金额必须是1dot+手续费，不然无法转出来，目前手续费一般都是0.00153左右，你转入一定的手续费就好了

**Comment by JFJun** [comment]
> 地址上只有一个dot 转0.9个节点报错，有办法可以把这种都转出来 吗
> 
> {
> "jsonrpc": "2.0",
> "error": {
> "code": 1010,
> "message": "Invalid Transaction",
> "data": "Inability to pay some fees (e.g. account balance too low)"
> },
> "id": 1
> }

如果只有一个dot是无法转账的，最小转账条件是1dot+手续费

**Comment by JFJun** [comment]
如果只有一个dot是无法转账的，最小转账条件是1dot+手续费
