### ISSUE TITLE
请问这个库支持PolkaDot吗？

### ISSUE THREAD

**Issue by sugeladi** [JFJun/substrate-go#3]
您好，Dot开启了转账，请问是否支持PolkaDot，如果支持的话，Dot是哪个值？

const (
	CallIdKusama = "0400"
	CallIdCrab   = "1400"
)

**Comment by JFJun** [comment]
> 您好，Dot开启了转账，请问是否支持PolkaDot，如果支持的话，Dot是哪个值？
> const (
> CallIdKusama = "0400"
> CallIdCrab   = "1400"
> )
是支持dot转账的，不过目前只支持Balances.transfer的区块解析和转账， 离线签名目前dot的callIdx是0500，这个值以后会更改为动态拿取

**Comment by JFJun** [comment]
是支持dot转账的，不过目前只支持Balances.transfer的区块解析和转账， 离线签名目前dot的callIdx是0500，这个值以后会更改为动态拿取

**Comment by sugeladi** [comment]
多谢，我这边设置为0500后，交易发送成功了。再次请教一下 这个值是从哪里的接口获取的？

**Comment by JFJun** [comment]
从metadata元数据里面解析出来的

**Comment by sugeladi** [comment]
好的 多谢。
