### ISSUE TITLE
Nonce重复不能提交交易

### ISSUE THREAD

**Issue by ghost** [JFJun/substrate-go#4]
提交两个交易，这两个交易相隔时间很短，导致获取到的nonce值相同，第二笔交易提交的时候会失败，这种事情应该咋处理，有没有好的办法。     如果我把nonce设置为0能不能解决？     谢谢    非常着急，希望看到的时候能回复下

**Comment by satonz** [comment]
@sugeladi

**Comment by ghost** [comment]
请问你是咋处理这个问题的@sugeladi

**Comment by ghost** [comment]
恳请大佬能抽空回复下   跪谢

**Comment by JFJun** [comment]
> 恳请大佬能抽空回复下   跪谢

你两笔交易之前的间隔是多少

**Comment by JFJun** [comment]
> 提交两个交易，这两个交易相隔时间很短，导致获取到的nonce值相同，第二笔交易提交的时候会失败，这种事情应该咋处理，有没有好的办法。     如果我把nonce设置为0能不能解决？     谢谢    非常着急，希望看到的时候能回复下

如果你的两笔之前的间隔时间较长，可以通过发送完一笔交易以后重新获取nonce值，如果时间较短，可以通过本地维护nonce值，没发送一笔+1，但是要注意如果你发送完以后from地址dot小于1，nonce就会重置为0，还有一种比较好的处理方式是通过批处理转账，就是同一个nonce的from地址往多个地址转账，但是这个包目前还不支持这种转账形式，后续会添加上

**Comment by ghost** [comment]
目前是不是查不到pending状态交易的nonce值

**Comment by sugeladi** [comment]
> 目前是不是查不到pending状态交易的nonce值

可以通过rpc接口获取到的， /accounts/地址/balance-info response里是有nonce字段的。 我的做法是JFJun说的 自己本地维护nonce，然后确保地址上最少保留1Dot，要不然nonce会被重置为0

**Comment by JFJun** [comment]
> 目前是不是查不到pending状态交易的nonce值

polkadot目前无法查询pending状态，目前这个包添加了Utility.batch(批量转账)的方法，你这个问题可以使用这个方法去转账

**Comment by ghost** [comment]
谢谢了
