### ISSUE TITLE
Transaction has a bad signature

### ISSUE THREAD

**Issue by crossle** [JFJun/substrate-go#5]
Use the single transfer transaction, bad signature

`ws resp error ,err={"code":1010,"data":"Transaction has a bad signature","message":"Invalid Transaction"}`

**Comment by JFJun** [comment]
I need more detailed information to solve this problem, such as which currency（dot or ksm） you are using and what is the transaction structure of the sending transaction.

**Comment by JFJun** [comment]
I need more detailed information to solve this problem, such as which currency（dot or ksm） you are using and what is the transaction structure of the sending transaction. @crossle

**Comment by crossle** [comment]
code like this

```
	c, err := rpc.New("wss://rpc.polkadot.io", "", "")
	if err != nil {
		return
	}
	btTx := tx.CreateTransaction("14aUbhkHhnqEuvUBxs586TEG72aVUdTT1QdC6i4kiDhyjRsL", "13mNncYHUy27hnEuh9xJAEubboMJ46cN7LA4FuvC8c6Cfz6f", 10000000000, 0, 0)
	btTx.SetGenesisHashAndBlockHash("0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", 1)
	callIdx, err := c.GetCallIdx("Balances", "transfer")
	if err != nil {
		return
	}
	btTx.SetSpecVersionAndCallId(uint32(c.SpecVersion), uint32(c.TransactionVersion), callIdx)
	btTx.SetSpecVersionAndCallId(25, 5, "0500")
	_, message, err := btTx.CreateEmptyTransactionAndMessage()
	if err != nil {
		fmt.Println(err)
		return
	}
	sig, err := btTx.SignTransaction("", message)
	if err != nil {
		fmt.Println(err)
		return
	}
	txHex, err := btTx.GetSignTransaction(sig)
	if err != nil {
		fmt.Println(err)
		return
	}
	//broadcast tx
	txidBytes, err := c.Rpc.SendRequest("author_submitExtrinsic", []interface{}{txHex})
	if err != nil {
		fmt.Println(err)
		return
	}
	txid := string(txidBytes)
	fmt.Println(txid)
``

**Comment by JFJun** [comment]
Some time ago. I use your sdk(https://github.com/crossle/arweave-go) to do AR transfers. This package helped me solve a lot of problems. Thank you very much for the open source package.  @crossle

**Comment by crossle** [comment]
> Some time ago. I use your sdk(https://github.com/crossle/arweave-go) to do AR transfers. This package helped me solve a lot of problems. Thank you very much for the open source package. @crossle

emmm. i just contribute a PR to convenient usage

**Comment by JFJun** [comment]
genesis hash is "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3" @crossle

**Comment by crossle** [comment]
> genesis hash is "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3" @crossle

OOOh, try it now

**Comment by crossle** [comment]
> 0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3

Thank you. It's work.

**Comment by crossle** [comment]
How about support ed25519 signature use golang ed25519?

**Comment by JFJun** [comment]
maybe you can use this method:
`func (t *ChainXTransaction) Sign(private, message string) (string, error) {
	message = Remove0X(message)
	messageBytes, err := hex.DecodeString(message)
	if err != nil {
		return "", err
	}
	private = Remove0X(private)
	priv, err1 := hex.DecodeString(private)
	if err1 != nil {
		return "", err1
	}
	//使用ed25519签名
	privKey := ed25519.NewKeyFromSeed(priv)
	sig := ed25519.Sign(privKey, messageBytes)
	if len(sig) != 64 {
		return "", errors.New("sign fail,sig length is not equal 64")
	}
	return hex.EncodeToString(sig), nil
}`
I use it to chainX ,but i do not use it to Polkadot,and you also need  set it to (https://github.com/JFJun/substrate-go/blob/master/tx/transaction.go --->p251) 0x00

**Comment by JFJun** [comment]
`func (t *ChainXTransaction) Sign(private, message string) (string, error) {
	message = Remove0X(message)
	messageBytes, err := hex.DecodeString(message)
	if err != nil {
		return "", err
	}
	private = Remove0X(private)
	priv, err1 := hex.DecodeString(private)
	if err1 != nil {
		return "", err1
	}
	//使用ed25519签名
	privKey := ed25519.NewKeyFromSeed(priv)
	sig := ed25519.Sign(privKey, messageBytes)
	if len(sig) != 64 {
		return "", errors.New("sign fail,sig length is not equal 64")
	}
	return hex.EncodeToString(sig), nil
}`

maybe you can use this method.
I use it to chainX ,but i do not use it to Polkadot,and you also need set it to (https://github.com/JFJun/substrate-go/blob/master/tx/transaction.go --->p251) 0x00

**Comment by crossle** [comment]
Thanks. I try it.
