### ISSUE TITLE
大佬可不可以支持下rio这条链

### ISSUE THREAD

**Issue by liuxh-go** [JFJun/substrate-go#6]
项目地址在这

https://github.com/RioDefi/riochain

**Comment by JFJun** [comment]
> 项目地址在这
> 
> https://github.com/RioDefi/riochain

目前还没有时间去弄了，如果也是substrate的链，可以根据这个包改一改

**Comment by liuxh-go** [comment]
我有点改不动...，感觉他的数据改了很多

**Comment by JFJun** [comment]
> 我有点改不动...，感觉他的数据改了很多

它的区块游览器都没有一笔交易

**Comment by JFJun** [comment]
> 我有点改不动...，感觉他的数据改了很多

你可以尝试使用github.com/JFJun/stafi-substrate-go这个包，看能否解决你的问题
