### ISSUE TITLE
Connecting to Westend gives the error

### ISSUE THREAD

**Issue by ChinmayPatel** [JFJun/substrate-go#7]
# Steps to reproduce: 

```
package main

import (
	"fmt"
	"github.com/JFJun/substrate-go/rpc"
}

func main() {
	client, _ := rpc.New("wss://westend-rpc.polkadot.io", "", "");

	blockHash:=string("0x7cea232f3bd8b87d6986f17c47738942ba290e83c5d57c53ffc71a44b9c6b743")
	block,_:=client.GetBlockByHash(blockHash)

	fmt.Println(block);
}
```

Running the code above gives me the error below; 

```
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/itering/scale.go/source.LoadTypeRegistry(0x18032d0, 0x0, 0x0, 0x0)
	/Users/blockx/go/pkg/mod/github.com/itering/scale.go@v0.7.0/source/source.go:20 +0xa31
github.com/JFJun/substrate-go/rpc.(*Client).registerTypes(0xc000068140)
	/Users/blockx/go/pkg/mod/github.com/!j!f!jun/substrate-go@v1.2.3/rpc/client.go:84 +0x108
github.com/JFJun/substrate-go/rpc.New(0x1581eee, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/blockx/go/pkg/mod/github.com/!j!f!jun/substrate-go@v1.2.3/rpc/client.go:54 +0x205
main.main()
	/Users/blockx/coding/polkadot/go-examples/main.go:18 +0x65

```

But, if I try to connect to the polkadot chain, it works. What could be the problem?

**Comment by JFJun** [comment]
> # Steps to reproduce:
> ```
> package main
> 
> import (
> 	"fmt"
> 	"github.com/JFJun/substrate-go/rpc"
> }
> 
> func main() {
> 	client, _ := rpc.New("wss://westend-rpc.polkadot.io", "", "");
> 
> 	blockHash:=string("0x7cea232f3bd8b87d6986f17c47738942ba290e83c5d57c53ffc71a44b9c6b743")
> 	block,_:=client.GetBlockByHash(blockHash)
> 
> 	fmt.Println(block);
> }
> ```
> 
> Running the code above gives me the error below;
> 
> ```
> panic: unexpected end of JSON input
> 
> goroutine 1 [running]:
> github.com/itering/scale.go/source.LoadTypeRegistry(0x18032d0, 0x0, 0x0, 0x0)
> 	/Users/blockx/go/pkg/mod/github.com/itering/scale.go@v0.7.0/source/source.go:20 +0xa31
> github.com/JFJun/substrate-go/rpc.(*Client).registerTypes(0xc000068140)
> 	/Users/blockx/go/pkg/mod/github.com/!j!f!jun/substrate-go@v1.2.3/rpc/client.go:84 +0x108
> github.com/JFJun/substrate-go/rpc.New(0x1581eee, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/Users/blockx/go/pkg/mod/github.com/!j!f!jun/substrate-go@v1.2.3/rpc/client.go:54 +0x205
> main.main()
> 	/Users/blockx/coding/polkadot/go-examples/main.go:18 +0x65
> ```
> 
> But, if I try to connect to the polkadot chain, it works. What could be the problem?

this package is not support the Westend blockchain

**Comment by JFJun** [comment]
> # Steps to reproduce:
> ```
> package main
> 
> import (
> 	"fmt"
> 	"github.com/JFJun/substrate-go/rpc"
> }
> 
> func main() {
> 	client, _ := rpc.New("wss://westend-rpc.polkadot.io", "", "");
> 
> 	blockHash:=string("0x7cea232f3bd8b87d6986f17c47738942ba290e83c5d57c53ffc71a44b9c6b743")
> 	block,_:=client.GetBlockByHash(blockHash)
> 
> 	fmt.Println(block);
> }
> ```
> 
> Running the code above gives me the error below;
> 
> ```
> panic: unexpected end of JSON input
> 
> goroutine 1 [running]:
> github.com/itering/scale.go/source.LoadTypeRegistry(0x18032d0, 0x0, 0x0, 0x0)
> 	/Users/blockx/go/pkg/mod/github.com/itering/scale.go@v0.7.0/source/source.go:20 +0xa31
> github.com/JFJun/substrate-go/rpc.(*Client).registerTypes(0xc000068140)
> 	/Users/blockx/go/pkg/mod/github.com/!j!f!jun/substrate-go@v1.2.3/rpc/client.go:84 +0x108
> github.com/JFJun/substrate-go/rpc.New(0x1581eee, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/Users/blockx/go/pkg/mod/github.com/!j!f!jun/substrate-go@v1.2.3/rpc/client.go:54 +0x205
> main.main()
> 	/Users/blockx/coding/polkadot/go-examples/main.go:18 +0x65
> ```
> 
> But, if I try to connect to the polkadot chain, it works. What could be the problem?

Maybe you can try to use this package[github.com/JFJun/stafi-substrate-go]. If the package doesn't support it, I can add the Westend for you

**Comment by ChinmayPatel** [comment]
Yes, the connection works. I've another question, but I'll close this issue and start a new issue. 

Thanks for the help.
