### ISSUE TITLE
dot提交交易nonce为64的时候,报Transaction has a bad signature

### ISSUE THREAD

**Issue by zenghq3** [JFJun/substrate-go#8]
其他nonce都可以发送交易成功, 唯独64的时候报签名失败.可以看看什么问题么?签名方式是sr25519

**Comment by JFJun** [comment]
如果你用dot或者bnc，建议你使用https://github.com/JFJun/bifrost-go.git这个包，如果是其他的链，可以使用https://github.com/JFJun/stafi-substrate-go.git这个包，这两个包签名基本和substrate-go是一样的。substrate-go这个包不进行维护了，目前有很多地方没有升级。后续那两个包会跟随主链去维护
